import yfinance as yf
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, classification_report
import joblib
import matplotlib.pyplot as plt

# ==========================================
# 1. DATA COLLECTION
# ==========================================
print("📥 Downloading data...")
data = yf.download("BTC-USD", interval="15m", period="60d")  # Use 15m, 60d for decent training data
data = data.dropna()
print(f"✅ Data shape: {data.shape}")

# ==========================================
# 2. INDICATOR ENGINE (Same as your backend)
# ==========================================
print("📊 Calculating indicators...")

# --- SMAs ---
data['SMA50'] = data['Close'].rolling(50).mean()
data['SMA200'] = data['Close'].rolling(200).mean()

# --- RSI ---
delta = data['Close'].diff()
gain = (delta.where(delta > 0, 0)).rolling(14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
rs = gain / loss
data['RSI'] = 100 - (100 / (1 + rs))

# --- ATR ---
high_low = data['High'] - data['Low']
high_close = abs(data['High'] - data['Close'].shift())
low_close = abs(data['Low'] - data['Close'].shift())
tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
data['ATR'] = tr.rolling(14).mean()

# --- Volume ---
data['Volume_Avg'] = data['Volume'].rolling(20).mean()

# ==========================================
# 3. FEATURE ENGINEERING (CRITICAL!)
# ==========================================
print("🛠️  Engineering features...")

# Normalized features
data['SMA50_Ratio'] = (data['Close'] - data['SMA50']) / data['SMA50']
data['SMA_Trend'] = (data['SMA50'] - data['SMA200']) / data['SMA200']
data['RSI_Norm'] = data['RSI'] / 100
data['Volatility_Norm'] = data['ATR'] / data['Close']
data['Volume_Norm'] = data['Volume'] / data['Volume_Avg']
data['Price_Change'] = data['Close'].pct_change()

# --- Additional Powerful Features ---
# 1. Rolling volatility (std dev of returns)
data['Rolling_Volatility'] = data['Price_Change'].rolling(20).std()

# 2. Simple price momentum
data['Price_Momentum'] = data['Close'] / data['Close'].shift(5) - 1

# 3. Trend strength (abs diff between SMAs)
data['Trend_Strength'] = abs(data['SMA50'] - data['SMA200']) / data['SMA200']

# --- Define final feature list ---
features = [
    'SMA50_Ratio',
    'SMA_Trend',
    'RSI_Norm',
    'Volatility_Norm',
    'Volume_Norm',
    'Price_Change',
    'Rolling_Volatility',
    'Price_Momentum',
    'Trend_Strength'
]

# ==========================================
# 4. CREATE TARGET VARIABLE
# ==========================================
print("🎯 Creating target variable...")
# Predict if price will be higher after 3 periods (e.g., 45 minutes for 15m data)
data['Target'] = (data['Close'].shift(-3) > data['Close']).astype(int)

# Drop NaN values generated by indicators and target
data = data.dropna()

# ==========================================
# 5. TRAIN/TEST SPLIT & MODEL TRAINING
# ==========================================
print("🚀 Training model...")

X = data[features]
y = data['Target']

# Use TimeSeriesSplit to avoid look-ahead bias
tscv = TimeSeriesSplit(n_splits=3)

model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

# Train on the last full split
for train_index, test_index in tscv.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        early_stopping_rounds=50,
        verbose=False
    )

# ==========================================
# 6. EVALUATION
# ==========================================
print("📈 Evaluating model...")
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# --- Feature Importance ---
importances = pd.Series(model.feature_importances_, index=features)
print("\n🔑 Top 5 Features:")
print(importances.sort_values(ascending=False).head(5))

# --- Plot Feature Importance ---
importances.sort_values().plot(kind='barh', figsize=(10, 6))
plt.title('Feature Importance')
plt.tight_layout()
plt.savefig('feature_importance.png')
print("📊 Feature importance plot saved as 'feature_importance.png'")

# ==========================================
# 7. SAVE MODEL & FEATURES LIST
# ==========================================
print("💾 Saving model and metadata...")
joblib.dump(model, "trading_model.pkl")

# Save feature list to ensure consistency between training and inference
with open("model_features.txt", "w") as f:
    for feature in features:
        f.write(f"{feature}\n")

print("✅ Model and features saved successfully!")

# Optional: Show a sample prediction
sample = X_test.iloc[[0]]
pred_prob = model.predict_proba(sample)[0][1]
print(f"\n🧪 Sample Prediction: UP Probability = {pred_prob:.4f}")